config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	get 'welcome/the_super_remote'
	get 'welcome/compatibility'
	get 'welcome/gallery'
	get 'welcome/reviews_and_press'
	get 'welcome/help'
	get 'welcome/about_us'
	get 'welcome/careers'
	get 'welcome/order_status'
	get 'welcome/legal'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	def the_super_remote
	end
	def compatibility
	end
	def gallery
	end
	def reviews_and_press
	end
	def help
	end
	def about_us
	end
	def careers
	end
	def order_status
	end
	def legal
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Item3
    meta name="viewport" content="width=device-width"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 

  body

    = yield 

app/views/shared/_footer.html.slim
footer.footer
  .container
    .row
      .footer__content
        ul.mnu.footer__mnu
          li.mnu__item
            = link_to "about_us", welcome_about_us_path, class: "mnu__link"
          li.mnu__item
            = link_to "careers", welcome_careers_path, class: "mnu__link"
          li.mnu__item
            = link_to "order_status", welcome_order_status_path, class: "mnu__link"
          li.mnu__item
            = link_to "legal", welcome_legal_path, class: "mnu__link"
        form.subscribe_form.footer__subscribe_form action=""
          p.subscribe_form__subscribe
            input.subscribe_form__text type="text" placeholder="Sign Up for Ray Newsletters"
            input.subscribe_form__submit type="submit" value="Subscribe"
        ul.social.footer__social
          li.social__item
            a.social__link href="#"
          li.social__item
            a.social__link href="#"
          li.social__item
            a.social__link href="#"
          li.social__item
            a.social__link href="#"
        p.copiraight &copy; 2014-2015 Ray Enterprises Inc. All rights reserved.

app/views/shared/_header.html.slim
header.header
  .container
    .row
      .top_line.header__top_line
        = link_to root_path, class: "top_line__logo_link" 
          = image_tag 'logo.png', alt: "Ray" 
        = link_to "pre-order", root_path, class: "button button-size-s button-txt_color-gray button__top_line" 
        nav.mnu
          li.mnu__item
            = link_to "the super remote", welcome_the_super_remote_path, class: "mnu__link" 
          li class="mnu__item"
            = link_to "compatibility", welcome_compatibility_path, class: 'mnu__link'
          li class="mnu__item"
            = link_to "gallery", welcome_gallery_path, class: 'mnu__link'
          li class="mnu__item"
            = link_to "reviews & press", welcome_reviews_and_press_path, class: "mnu__link"
          li class="mnu__item"
            = link_to "help", welcome_help_path, class: "mnu__link"

app/views/welcome/about_us.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title About Us page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/careers.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Careers page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/compatibility.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Comatibility page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/gallery.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Gallery page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/help.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Help page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/index.html.slim
= render partial: "shared/header" 
= render partial: "welcome/shared/top" 
= render partial: "welcome/shared/devices" 
= render partial: "welcome/shared/compatibility" 
= render partial: "welcome/shared/questions" 
= render partial: "welcome/shared/remote" 
= render partial: "shared/footer" 

app/views/welcome/legal.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Legal page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/order_status.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Order Status page
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/reviews_and_press.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title Reviews &amp; Presspage
    p.text.text-size-s.top__text
     | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"

app/views/welcome/shared/_compatibility.html.slim
section.compatibility
		.container
			.row
				h1.ray_title-h1.ray_title-h1-light Enabled with Wi-Fi, Infrared, ZigBee and Bluetooth technologies, Ray is the HQ of your entertainment.
				ul.producers.compatibility__producers
					l.producers__col
						ul.producers__list
							li.producers__list_item
								a.producers__title href="#" Televisions
							li.producers__list_item
								a.producers__title href="#" LG
							li.producers__list_item
								a.producers__title href="#" Samsung
							li.producers__list_item
								a.producers__title href="#" Sharp
							li.producers__list_item
								a.producers__title href="#" Sony
							li.producers__list_item
								a.producers__title href="#" Vizio
							li.producers__list_item
								a.producers__title href="#" and more
					li.producers__col
						ul.producers__list
							li.producers__list_item 
								a.producers__title href="#" Set-Top Boxes
							li.producers__list_item 
								a.producers__title href="#" Arris
							li.producers__list_item 
								a.producers__title href="#" Cisco
							li.producers__list_item 
								a.producers__title href="#" Motorola
							li.producers__list_item 
								a.producers__title href="#" Samsung
							li.producers__list_item 
								a.producers__title href="#" Scientific Atlanta
							li.producers__list_item 
								a.producers__title href="#" and more</li>
					li.producers__col
						ul.producers__list
							li.producers__list_item
								a.producers__title href="#" Receivers &amp; Soundbars
							li.producers__list_item
								a.producers__title href="#" Onkyo
							li.producers__list_item
								a.producers__title href="#" Pioneer
							li.producers__list_item
								a.producers__title href="#" Samsung
							li.producers__list_item
								a.producers__title href="#" Sony
							li.producers__list_item
								a.producers__title href="#" Yamaha
							li.producers__list_item
								a.producers__title href="#" and more
					li.producers__col
						ul.producers__list
							li.producers__list_item
								a.producers__title href="#" Blu-ray &amp; DVD Players
							li.producers__list_item
								a.producers__title href="#" LG
							li.producers__list_item
								a.producers__title href="#" Samsung
							li.producers__list_item
								a.producers__title href="#" Sharp
							li.producers__list_item
								a.producers__title href="#" Sony
							li.producers__list_item
								a.producers__title href="#" Vizio
							li.producers__list_item
								a.producers__title href="#" and more
					li.producers__col
						ul.producers__list
							li.producers__list_item
								a.producers__title href="#" Streaming Devices
							li.producers__list_item
								a.producers__title href="#" Apple TV
							li.producers__list_item
								a.producers__title href="#" Roku
							li.producers__list_item
								a.producers__title href="#" Xbox 360
							li.producers__list_item
								a.producers__title href="#" Xbox One
							li.producers__list_item
								a.producers__title href="#" and more
				a.button.button-size-m.button-txt_color-white href="#" check compatibility

app/views/welcome/shared/_devices.html.slim
section.devices
		.container
			.row
				.devices__stickers
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'tv.png', alt: "Televisions"
						span.device__label Televisions
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'set_top_boxes.png', alt: "Set-Top Boxes"
						span.device__label Set-Top Boxes
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'receivers_soundbars.png', alt: "Receivers & Soundbars"
						span.device__label Receivers &amp; Soundbars
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'dvd.png', alt: "Blu-ray & DVD Players"
						span.device__label Blu-ray &amp; DVD Players
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'apple_tv.png', alt: "Apple TV"
						span.device__label Apple TV
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'roku.png', alt: "Roku"
						span.device__label Roku
					a.device.devices__device href="#"
						.device__sticker
							= image_tag 'xbox.png', alt: "Xbox 360 & One"
						span.device__label Xbox 360 &amp; One

				.devices__text_block
					h1.ray_title-h1.ray_title-h1-dark.devices__ray_title
						| Ray connects to everything. Thousands of devices in your home to be exact.
					p.text.text-size-s
						| (Yes, you read that right.) So in a matter of minutes, your  
						a.link href="#" TV
						| , 
						a.link href="#" set-top box
						| , 
						a.link href="#" Apple TV
						| , 
						a.link href="#" Roku
						| , 
						a.link href="#" Xbox
						| , 
						a.link href="#" DVD player
						| , 
						a.link href="#" Blu-Ray
						| , 
						a.link href="#" home stereo
						| and any other intelligent device in your house locks into Ray for central command control awesomeness.

app/views/welcome/shared/_questions.html.slim
section.questions
	.container
		.row
			h1.ray_title-h1.ray_title-h1-dark.ray_title-h1-capitalize frequently asked questions
			.questions__content.clear_fix
				.questions__text_block
					h3.ray_title-h3.questions__ray_title Question goes here?
					p.text.text-size-m
						| Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
				.questions__text_block
					h3.ray_title-ray_title-h3.questions__ray_title Question goes here?
					p.text.text-size-m 
						| Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
				.questions__text_block
					h3.ray_title-h3.questions__ray_title Question goes here?
					p.text.text-size-m
						| Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
				.questions__text_block
					h3.ray_title-ray_title-h3.questions__ray_title Question goes here?
					p.text.text-size-m 
						| Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
			a.button.button-size-m.button-txt_color-gray href="#" learn more

app/views/welcome/shared/_remote.html.slim
section.remote
	.container
		.row
			a.remote_item href="#"
				= image_tag "Meet_Ray.png", class:"remote_item__img"
				span.remote_item__cover_bg Meet Ray
			a.remote_item href="#"
				= image_tag "Search.png", class:"remote_item__img"
				span.remote_item__cover_bg Search
			a.remote_item href="#"
				= image_tag "Discovery.png", class:"remote_item__img"
				span.remote_item__cover_bg Discovery
			a.remote_item href="#"
				= image_tag "Kids.png", class:"remote_item__img"
				span.remote_item__cover_bg Kids
			a.remote_item href="#"
				= image_tag "DISH.png", class:"remote_item__img"
				span.remote_item__cover_bg DISH Network on Ray
			a.remote_item href="#"
				= image_tag "Universal_Remote.png", class:"remote_item__img"
				span.remote_item__cover_bg Universal Remote
			a.remote_item href="#"
				= image_tag "Streaming.png", class:"remote_item__img"
				span.remote_item__cover_bg Streaming
			a.remote_item href="#"
				= image_tag "Super_Easy_Set_up.png", class:"remote_item__img"
				span.remote_item__cover_bg Super Easy Set Up
			a.remote_item href="#"
				= image_tag "Tech_Specs.png", class:"remote_item__img"
				span.remote_item__cover_bg Tech Specs

app/views/welcome/shared/_top.html.slim
section.top
  .container
    .row
      .top__text_block
        h2.ray_title-h2.top__ray_title Universal Remote
        h1.ray_title-h1.ray_title-h1-dark.top__ray_title All your remotes bundled into one: The last remote control you’ll ever use? Totally.
        p.text.text-size-s.top__text
          | Most families have their TV remote, their cable remote, their DVD remote, their soundbar remote, their Roku remote , etc. With Ray, that's a thing of the past . No more looking at hunks of plastic and asking yourself what does what. Once Ray is connected, it combines the features and functions of all your remotes and make the experience of controlling your entertainment even better. That’s not really an exaggeration, either. In fact, the only thing Ray can't do is grab that pint of peanut butter cup ice cream from the freezer and feed it to you. The future: It’s just so easy.
  .container
    .row
      .banner
        = image_tag 'banner.png', class: "banner__img", alt: "Banner"

app/views/welcome/the_super_remote.html.slim
= render partial: "shared/header"
.container
  .row
    h1.ray_title-h1.ray_title-h1-dark.top__ray_title The Super Remote Page
    p.text.text-size-s.top__text
      | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, amet quos doloremque ea inventore    excepturi, magnam quasi, omnis iure in est pariatur perferendis! Quos dolorem quam sapiente neque,   ducimus atque non! Impedit aspernatur voluptates, pariatur qui! Rem maiores nulla harum reprehenderit    commodi ipsa possimus omnis maxime illo dignissimos natus unde labore, fugit, dolores quisquam corrupti   ad officia illum velit soluta aspernatur blanditiis alias. Et ullam veniam tenetur sed assumenda placeat     magni cupiditate distinctio dolorem atque? Pariatur animi accusamus totam, sequi cumque, quod distinctio    est vitae quia mollitia architecto cupiditate quibusdam esse, expedita aperiam asperiores repudiandae   quos. Accusantium, sequi non harum!
= render partial: "shared/footer"